-- SEED PARA BASE DE DATOS SELLER
TRUNCATE TABLE products CASCADE;
TRUNCATE TABLE stores CASCADE;

-- INSERTING STORES
INSERT INTO stores (id, name, email, category, image_url, address, lat, lng) VALUES ('store_pizzeria_roma', 'Pizzería Roma', 'contacto@pizzeriaroma.com', 'Gastronomía', 'https://via.placeholder.com/150', 'Alsina 300, Bahía Blanca', -38.718, -62.266) ON CONFLICT (id) DO NOTHING;
INSERT INTO stores (id, name, email, category, image_url, address, lat, lng) VALUES ('store_tecnologia_sur', 'TecnoSur', 'ventas@tecnosur.com', 'Tecnología', 'https://via.placeholder.com/150', 'Chiclana 200, Bahía Blanca', -38.716, -62.266) ON CONFLICT (id) DO NOTHING;
INSERT INTO stores (id, name, email, category, image_url, address, lat, lng) VALUES ('store_farmacia_centro', 'Farmacia del Centro', 'farmacia@centro.com', 'Farmacia', 'https://via.placeholder.com/150', 'O''Higgins 50, Bahía Blanca', -38.7185, -62.2665) ON CONFLICT (id) DO NOTHING;
INSERT INTO stores (id, name, email, category, image_url, address, lat, lng) VALUES ('store_libreria_estudiantil', 'Librería Estudiantil', 'hola@libreria.com', 'Librería', 'https://via.placeholder.com/150', 'Alem 1100, Bahía Blanca', -38.706, -62.264) ON CONFLICT (id) DO NOTHING;
INSERT INTO stores (id, name, email, category, image_url, address, lat, lng) VALUES ('store_supermercado_todo', 'Super Todo', 'info@supertodo.com', 'Supermercado', 'https://via.placeholder.com/150', 'Sarmiento 400, Bahía Blanca', -38.713, -62.2675) ON CONFLICT (id) DO NOTHING;

-- INSERTING PRODUCTS
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('a1b2c3d4-e5f6-4a1b-8c2d-3e4f5a6b7c8d', 'store_pizzeria_roma', 'Pizza Muzzarella', 6500, 100, 'Clásica pizza de muzzarella con aceitunas verdes', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('b2c3d4e5-f6a1-4b2c-8d3e-4f5a6b7c8d9e', 'store_pizzeria_roma', 'Pizza Especial', 8000, 50, 'Muzzarella, jamón cocido, morrones y huevo', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('c3d4e5f6-a1b2-4c3d-8e4f-5a6b7c8d9e0f', 'store_pizzeria_roma', 'Docena de Empanadas', 9600, 30, '12 empanadas fritas u horneadas a elección', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('d4e5f6a1-b2c3-4d4e-8f5a-6b7c8d9e0f1a', 'store_pizzeria_roma', 'Cerveza Artesanal IPA', 3500, 150, 'Cerveza IPA 1 litro, en envase retornable', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('e5f6a1b2-c3d4-4e5f-8a6b-7c8d9e0f1a2b', 'store_tecnologia_sur', 'Auriculares Inalámbricos', 25000, 30, 'Auriculares bluetooth con cancelación de ruido', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('f6a1b2c3-d4e5-4f6a-8b7c-8d9e0f1a2b3c', 'store_tecnologia_sur', 'Cargador Rápido USB-C', 12000, 100, 'Cargador de pared 20W para smartphones', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('a1b2c3d4-e5f6-4a1b-8c2d-9e0f1a2b3c4d', 'store_tecnologia_sur', 'Funda de Silicona', 4500, 80, 'Funda antigolpes para varios modelos', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('b2c3d4e5-f6a1-4b2c-8d3e-0f1a2b3c4d5e', 'store_tecnologia_sur', 'Cable USB-C de 2m', 3000, 120, 'Cable mallado reforzado de carga rápida', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('c3d4e5f6-a1b2-4c3d-8e4f-1a2b3c4d5e6f', 'store_farmacia_centro', 'Alcohol en Gel 500ml', 2000, 200, 'Alcohol en gel al 70%', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('d4e5f6a1-b2c3-4d4e-8f5a-2b3c4d5e6f7a', 'store_farmacia_centro', 'Ibuprofeno 400mg', 1500, 500, 'Caja x 10 comprimidos', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('e5f6a1b2-c3d4-4e5f-8a6b-3c4d5e6f7a8b', 'store_farmacia_centro', 'Pasta Dental', 2200, 150, 'Pasta con flúor 90g triple acción', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('f6a1b2c3-d4e5-4f6a-8b7c-4d5e6f7a8b9c', 'store_farmacia_centro', 'Shampoo Anticaspa', 4100, 60, 'Shampoo cuidado diario 400ml', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('a1b2c3d4-e5f6-4a1b-8c2d-5e6f7a8b9c0d', 'store_libreria_estudiantil', 'Cuaderno Universitario', 5000, 300, 'Cuaderno espiralado rayado 84 hojas', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('b2c3d4e5-f6a1-4b2c-8d3e-6f7a8b9c0d1e', 'store_libreria_estudiantil', 'Resaltadores x4', 3500, 100, 'Pack de 4 resaltadores colores pastel', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('c3d4e5f6-a1b2-4c3d-8e4f-7a8b9c0d1e2f', 'store_libreria_estudiantil', 'Bolígrafo Azul', 800, 500, 'Bolígrafo trazo fino 1.0mm', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('d4e5f6a1-b2c3-4d4e-8f5a-8b9c0d1e2f3a', 'store_libreria_estudiantil', 'Mochila Escolar', 35000, 20, 'Mochila urbana reforzada con porta notebook', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('e5f6a1b2-c3d4-4e5f-8a6b-9c0d1e2f3a4b', 'store_supermercado_todo', 'Leche Entera 1L', 1100, 1000, 'Leche larga vida en sachet', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('f6a1b2c3-d4e5-4f6a-8b7c-0d1e2f3a4b5c', 'store_supermercado_todo', 'Fideos Spaghetti', 1300, 400, 'Fideos secos paquete de 500g', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('a1b2c3d4-e5f6-4a1b-8c2d-1e2f3a4b5c6d', 'store_supermercado_todo', 'Puré de Tomate', 900, 600, 'Puré de tomate tetra brik 520g', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('b2c3d4e5-f6a1-4b2c-8d3e-2f3a4b5c6d7e', 'store_supermercado_todo', 'Yerba Mate', 3200, 250, 'Yerba mate suave paquete 500g', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, store_id, name, price, stock, description, image_url) VALUES ('c3d4e5f6-a1b2-4c3d-8e4f-3a4b5c6d7e8f', 'store_supermercado_todo', 'Galletitas Dulces', 1500, 300, 'Galletitas de chocolate con relleno dulce', 'https://via.placeholder.com/150') ON CONFLICT (id) DO NOTHING;
